// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/xmltojson/xmltojson.d.ts
declare module 'xmltojson' {

    export = xmltojson;

    namespace xmltojson {
        function grokType(sValue: any): any;
        function parseString(xmlString: string, opt: Options): Object;
        function parseXml(oXMLParent: Document, opt: Options): Object;
        function xmlToString(xmlDoc: Document): string;
        function stringToXml(xmlString: string): Document;

        interface Options {
            mergeCDATA?: boolean,
            grokAttr?: boolean,
            grokText?: boolean,
            normalize?: boolean,
            xmlns?: boolean,
            namespaceKey?: string,
            textKey?: string,
            valueKey?: string,
            attrKey?: string,
            cdataKey?: string,
            attrsAsObject?: boolean,
            stripAttrPrefix?: boolean,
            stripElemPrefix?: boolean,
            childrenAsArray?: boolean
        }
    }
}
