/* Generated by SharpKit 5 v5.4.9 */

if (typeof(corexjs) == "undefined")
    var corexjs = {};
corexjs.Utils = function (){
};
corexjs.Utils.Prop = function (prop){
    var code;
    if (prop["isDelegate"])
        code = prop["func"].toString();
    else
        code = prop.toString();
    return code.substringBetween(".", ";");
};
corexjs.Utils.ItemProp = function (list, prop){
    return corexjs.Utils.Prop(prop);
};

