/* Generated by SharpKit 5 v5.4.9 */

if (typeof(dbr) == "undefined")
    var dbr = {};
dbr.DefaultPage2 = function (){
    this.Res = null;
    this.grdFiles = null;
    this.tbPath = null;
    this.btnGroup = null;
    this.Req = null;
    this.Win = null;
    this.Service = null;
    this.El = null;
    this.ActiveFile = null;
    $($CreateDelegate(this, this.OnDomReady));
    this.Service = new dbr.SiteServiceClient();
    this.Res = {
        Relatives: {}
    };
};
dbr.DefaultPage2.prototype.get_Path = function (){
    return this.Req.Path;
};
dbr.DefaultPage2.prototype.OnDomReady = function (){
    this.Win = window;
    this.El = $("body");
    this.grdFiles = this.El.getAppend("#grdFiles.Grid");
    this.btnGroup = this.grdFiles.getAppend(".btn-group");
    var btns =  [{
        Id: "GotoParentDir",
        Text: "Up",
        Action: $CreateAnonymousDelegate(this, function (){
            this.GotoFolder(this.Res.Relatives.ParentFolder);
        })
    }, {
        Id: "GotoPrevSibling",
        Text: "Prev",
        Action: $CreateAnonymousDelegate(this, function (){
            this.GotoFolder(this.Res.Relatives.PreviousSibling);
        })
    }, {
        Id: "GotoNextSibling",
        Text: "Next",
        Action: $CreateAnonymousDelegate(this, function (){
            this.GotoFolder(this.Res.Relatives.NextSibling);
        })
    }, {
        Id: "Folders",
        Text: "Folders",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.HideFolders = !this.Req.HideFolders;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Files",
        Text: "Files",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.HideFiles = !this.Req.HideFiles;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Mix",
        Text: "Mix",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.MixFilesAndFolders = !this.Req.MixFilesAndFolders;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Size",
        Text: "Size",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.FolderSize = !this.Req.FolderSize;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Keep",
        Text: "Keep",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.KeepView = !this.Req.KeepView;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Hidden",
        Text: "Hidden",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.ShowHiddenFiles = !this.Req.ShowHiddenFiles;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Recursive",
        Text: "Recursive",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Req.IsRecursive = !this.Req.IsRecursive;
            this.SaveReqListAndRender();
        })
    }, {
        Id: "Subs",
        Text: "Subs",
        Action: $CreateAnonymousDelegate(this, function (){
            this.OpenInNewWindow(this.GetSubtitleSearchLink(this.Res.File));
        })
    }, {
        Id: "Imdb",
        Text: "Imdb",
        Action: $CreateAnonymousDelegate(this, function (){
            this.OpenInNewWindow(this.GetSubtitleSearchLink(this.Res.File));
        })
    }, {
        Id: "Delete",
        Text: "Delete",
        Action: $CreateDelegate(this, this.GotoNextSibling)
    }, {
        Id: "Explore",
        Text: "Explore",
        Action: $CreateAnonymousDelegate(this, function (){
            this.Execute(this.Res.File, $CreateAnonymousDelegate(this, function (res){
                console.info(res);
            }));
        })
    }
    ];
    btns.forEach($CreateDelegate(this, this.AddButton));
    this.tbPath = this.grdFiles.getAppend("input.form-control.Path").change($CreateAnonymousDelegate(this, function (e){
        this.GotoPath(this.tbPath.val());
    }));
    this.Req = {};
    this.LoadReq();
    this.tbPath.val(this.Req.Path);
    this.ListFiles($CreateDelegate(this, this.Render));
    this.Win.onpopstate = $CreateAnonymousDelegate(this, function (e){
        this.LoadReq();
        this.ListAndRender();
    });
};
dbr.DefaultPage2.prototype.OpenInNewWindow = function (p){
    this.Win.open(p, "_blank");
};
dbr.DefaultPage2.prototype.LoadReq = function (){
    QueryString.parse(null, this.Req, null);
    var path = decodeURI(window.location.pathname);
    if (path == "/"){
        path = "";
    }
    else if (path.startsWith("//")){
        var tokens = path.split("/");
        path = tokens.join("\\");
    }
    else {
        path = path.substr(1);
        var tokens = path.split("/");
        tokens[0] += ":";
        path = tokens.join("\\");
    }
    if (path.endsWith("\\"))
        path = dbr.SiteExtensions.removeLast(path, 1);
    this.Req.Path = path;
};
dbr.DefaultPage2.prototype.AddButton = function (btn){
    this.btnGroup.getAppend("button.btn.btn-default#btn" + btn.Id).text(btn.Text).click(btn.Action);
};
dbr.DefaultPage2.prototype.ListFiles = function (cb){
    this.Service.ListFiles(this.Req, $CreateAnonymousDelegate(this, function (res){
        this.Res = res;
        dbr.Extensions2.Trigger(cb);
    }));
};
dbr.DefaultPage2.prototype.GotoPrevSibling = function (){
    this.GotoFolder(this.Res.Relatives.PreviousSibling);
};
dbr.DefaultPage2.prototype.GotoNextSibling = function (){
    this.GotoFolder(this.Res.Relatives.NextSibling);
};
dbr.DefaultPage2.prototype.GotoParentDir = function (){
    this.GotoFolder(this.Res.Relatives.ParentFolder);
};
dbr.DefaultPage2.prototype.GotoFolder = function (file){
    if (file == null || !file.IsFolder)
        return;
    this.GotoPath(file.Path);
};
dbr.DefaultPage2.prototype.GotoPath = function (path){
    this.Req.Path = path;
    this.SaveReqListAndRender();
};
dbr.DefaultPage2.prototype.SaveReq = function (){
    var state = Q.copy(this.Req);
    var path = state.Path;
    if (path.length > 0){
        var isNetworkShare = path.startsWith("\\\\");
        if (isNetworkShare)
            path = path.substr(1);
        var tokens = path.split("\\");
        if (!isNetworkShare)
            tokens[0] = tokens[0].replaceAll(":", "");
        path = tokens.join("/");
        path = encodeURI(path);
        path = "/" + path;
        if (!path.endsWith("/"))
            path += "/";
    }
    delete state.Path;
    var q = QueryString.stringify(state);
    if (Q.isNotNullOrEmpty(q))
        q = "?" + q;
    var url = location.origin + path + q;
    var win = window;
    win.history.pushState(state, this.Req.Path, url);
};
dbr.DefaultPage2.prototype.SaveReqListAndRender = function (){
    this.SaveReq();
    this.ListAndRender();
};
dbr.DefaultPage2.prototype.ListAndRender = function (){
    this.ListFiles($CreateDelegate(this, this.Render));
};
dbr.DefaultPage2.prototype.Render = function (){
    this.tbPath.val(this.get_Path());
    this.RenderGrid();
};
dbr.DefaultPage2.prototype.RenderGrid = function (){
    this.grdFiles.off();
    var gridOptions = {
        Items: this.Res.Files,
        Columns: [{
            Prop: function (t){
                return t.Name;
            },
            Width: null,
            RenderCell: $CreateDelegate(this, this.RenderNameCell)
        }, {
            Prop: function (t){
                return t.Modified;
            },
            Width: 150,
            Format: $CreateDelegate(this, this.FormatFriendlyDate)
        }, {
            Prop: function (t){
                return t.Size;
            },
            Width: 150
        }, {
            Prop: function (t){
                return t.Extension;
            },
            Width: 150
        }
        ],
        RowClass: $CreateDelegate(this, this.GetRowClass),
        PageSize: 100
    };
    this.grdFiles.Grid(gridOptions);
    var grid = corexjs.ui.grid.Grid.Get(this.grdFiles);
    this.grdFiles.mousedown($CreateAnonymousDelegate(this, function (e){
        var target = $(e.target);
        var file = grid.GetItem(target);
        if (file == null)
            return;
        this.ClickFile(file, e.ctrlKey, e.shiftKey);
    }));
    this.grdFiles.click($CreateAnonymousDelegate(this, function (e){
        var target = $(e.target);
        var file = grid.GetItem(target);
        if (file == null)
            return;
        if (!target.is("a.Name"))
            return;
        e.preventDefault();
        this.Open(file);
    }));
    this.grdFiles.dblclick($CreateAnonymousDelegate(this, function (e){
        var target = $(e.target);
        var file = grid.GetItem(target);
        if (file == null)
            return;
        e.preventDefault();
        this.Open(file);
    }));
};
dbr.DefaultPage2.prototype.ClickFile = function (file, ctrl, shift){
    if (ctrl){
        if (this.ActiveFile == file)
            this.ActiveFile = null;
        else
            this.ActiveFile = file;
    }
    else if (shift){
        this.ActiveFile = file;
    }
    else {
        this.ActiveFile = file;
    }
};
dbr.DefaultPage2.prototype.Open = function (file){
    if (file == null)
        return;
    if (file.IsFolder){
        this.GotoFolder(file);
        return;
    }
    var prompt = false;
    if (file.Extension != null){
        var ext = file.Extension.toLowerCase();
        var blackList =  [".exe", ".bat", ".com"];
        if (blackList.contains(ext)){
            prompt = true;
        }
    }
    else {
        prompt = true;
    }
    if (prompt && !this.Win.confirm("This is an executable file, are you sure you want to run it?"))
        return;
    this.Execute(file, $CreateAnonymousDelegate(this, function (res){
        console.info(res);
    }));
};
dbr.DefaultPage2.prototype.Execute = function (file, cb){
    this.Service.Execute({
        Path: file.Path
    }, cb);
};
dbr.DefaultPage2.prototype.FormatFriendlyDate = function (arg){
    return dbr.SiteExtensions.ToFriendlyRelative2(dbr.SiteExtensions.ToDefaultDate(arg), null);
};
dbr.DefaultPage2.prototype.RenderNameCell = function (col, file, td){
    td.getAppend("a.Name").text(file.Name).attr("href", "javascript:void(0)");
};
dbr.DefaultPage2.prototype.GetRowClass = function (file, index){
    if (file.IsFolder)
        return "FolderRow";
    return "FileRow";
};
dbr.DefaultPage2.prototype.GetSubtitleSearchLink = function (File){
    if (File == null)
        return null;
    var s = this.GetFilenameForSearch(File.Name);
    return "https://www.google.com/search?q=" + encodeURIComponent(s + " eng subscene");
};
dbr.DefaultPage2.prototype.GetGoogleSearchLink = function (File){
    if (File == null)
        return null;
    var s = this.GetFilenameForSearch(File.Name);
    return "https://www.google.com/search?q=" + encodeURIComponent(s);
};
dbr.DefaultPage2.prototype.GetFilenameForSearch = function (s){
    var tokens = s.split(new RegExp("[ \\.\\-]")).select($CreateAnonymousDelegate(this, function (t){
        return t.toLowerCase();
    }));
    var ignoreWords =  ["xvid", "720p", "1080p", "dimension", "sample", "nfo", "par2"].selectToObject($CreateAnonymousDelegate(this, function (t){
        return t;
    }), $CreateAnonymousDelegate(this, function (t){
        return true;
    }));
    var list =  [];
    for (var $i2 = 0,$l2 = tokens.length,token = tokens[$i2]; $i2 < $l2; $i2++, token = tokens[$i2]){
        if (ignoreWords[token])
            break;
        if (token.length == 3){
            var season = this.TryParse(token.substr(0, 1));
            var episode = this.TryParse(token.substr(1));
            if (season != null && episode != null && episode < 30){
                var normalized = "S" + season.format("00") + "E" + episode.format("00");
                list.push(normalized);
                break;
            }
        }
        list.push(token);
    }
    var s2 = list.join(" ");
    return s2;
};
dbr.DefaultPage2.prototype.TryParse = function (s){
    var x = parseInt(s);
    if (isNaN(x))
        return null;
    return x;
};

