/* Generated by SharpKit 5 v5.4.9 */
if (typeof ($Inherit) == 'undefined') {
	var $Inherit = function (ce, ce2) {

		if (typeof (Object.getOwnPropertyNames) == 'undefined') {

			for (var p in ce2.prototype)
				if (typeof (ce.prototype[p]) == 'undefined' || ce.prototype[p] == Object.prototype[p])
					ce.prototype[p] = ce2.prototype[p];
			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		} else {

			var props = Object.getOwnPropertyNames(ce2.prototype);
			for (var i = 0; i < props.length; i++)
				if (typeof (Object.getOwnPropertyDescriptor(ce.prototype, props[i])) == 'undefined')
					Object.defineProperty(ce.prototype, props[i], Object.getOwnPropertyDescriptor(ce2.prototype, props[i]));

			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		}

	}
};

if (typeof($CreateException)=='undefined') 
{
    var $CreateException = function(ex, error) 
    {
        if(error==null)
            error = new Error();
        if(ex==null)
            ex = new System.Exception.ctor();       
        error.message = ex.message;
        for (var p in ex)
           error[p] = ex[p];
        return error;
    }
}

if (typeof ($CreateAnonymousDelegate) == 'undefined') {
    var $CreateAnonymousDelegate = function (target, func) {
        if (target == null || func == null)
            return func;
        var delegate = function () {
            return func.apply(target, arguments);
        };
        delegate.func = func;
        delegate.target = target;
        delegate.isDelegate = true;
        return delegate;
    }
}


var IsIE6 = false;
var IsWebKit = false;
IsIE6 = ((window.navigator.userAgent.indexOf("MSIE 6.") != -1) && (window.navigator.userAgent.indexOf("Opera") == -1));
IsWebKit = (window.navigator.userAgent.indexOf("AppleWebKit") != -1);
function ApplyExactTemplate(el, template){
    if (el.getAttribute("_IsTemplated"))
        return null;
    el.setAttribute("_IsTemplated", true);
    var tmp = template.cloneNode(true);
    tmp.id = "";
    $(el).replaceWith(tmp);
    $("#Element", tmp).replaceWith(el);
    return tmp;
};
function ApplyTemplates(){
    $("#Templates").children().each(function (i, templateEl){
        templateEl.setAttribute("_IsTemplated", true);
        var className = "." + templateEl.id;
        $(className).each(function (index, t){
            ApplyExactTemplate(t, templateEl);
        });
    });
};
function ApplyTemplate(el){
    var className = el.className;
    if (className.length > 0){
        var templateEl = document.getElementById(className);
        if (templateEl != null && templateEl.parentElement.id == "Templates")
            return ApplyExactTemplate(el, templateEl);
    }
    return null;
};
function ParseQueryString(search){
    var obj = new Object();
    var pairs = search.substring(1).split("&");
    for (var $i2 = 0,$l2 = pairs.length,pair = pairs[$i2]; $i2 < $l2; $i2++, pair = pairs[$i2]){
        var tokens = pair.split("=");
        obj[decodeURIComponent(tokens[0])] = decodeURIComponent(tokens[1]);
    }
    return obj;
};
function GetFormData(inputMappings, suffix){
    var obj2 = inputMappings;
    var data = new Object();
    for (var p in obj2){
        var id = obj2[p];
        if (suffix != null)
            id += suffix;
        var input = document.getElementById(id);
        if (input == null)
            continue;
        if (input.type == "checkbox")
            data[p] = input.checked;
        else
            data[p] = input.value;
    }
    return data;
};
function GetRepeatedFormData(inputMappings){
    var list =  [];
    var i = 0;
    while (true){
        i++;
        var data = GetFormData(inputMappings, i.toString());
        if (data == null)
            return list;
        list.push(data);
    }
};
function FixBrowserCompatibilityIssues(){
    if (IsIE6 || IsWebKit){
        $("a").each(function (i, el){
            FixAnchor(el);
        });
    }
};
function FixAnchor(el){
    if (el == null || el.nodeName != "A")
        return;
    if (!IsWebKit)
        return;
    var a = el;
    if (a.href == null || a.href.length == 0)
        a.href = "javascript:void(0);";
};
function SmoothScrollTo(id){
    $("html,body").animate({
        scrollTop: $("#" + id).offset().top
    }, "slow");
};
function SmoothScrollToTop(){
    $("html,body").animate({
        scrollTop: 0
    }, "slow");
};
if (typeof(DesktopBrowser) == "undefined")
    var DesktopBrowser = {};
if (typeof(DesktopBrowser.Client) == "undefined")
    DesktopBrowser.Client = {};
if (typeof(DesktopBrowser.Client.Utils) == "undefined")
    DesktopBrowser.Client.Utils = {};
DesktopBrowser.Client.Utils.JsArrayEnumerator = function (array){
    this.Array = null;
    this.Index = 0;
    this.Array = array;
    this.Index = -1;
};
DesktopBrowser.Client.Utils.JsArrayEnumerator.prototype.MoveNext = function (){
    this.Index++;
    return this.Index < this.Array.length;
};
DesktopBrowser.Client.Utils.JsArrayEnumerator.prototype.get_Current = function (){
    return this.Array[this.Index];
};
DesktopBrowser.Client.Utils.JsArrayEnumerator.prototype.Dispose = function (){
};
DesktopBrowser.Client.Utils.JsArrayEnumerator.prototype.Reset = function (){
    this.Index = -1;
};
Array.prototype.GetEnumerator = function (){
    return new DesktopBrowser.Client.Utils.JsArrayEnumerator(this);
};
$Inherit(Array, Array);
DesktopBrowser.Client.Utils.JsExtensions = function (){
};
DesktopBrowser.Client.Utils.JsExtensions.Trim = function (s){
    return s.replace(new RegExp("^\\s*"), "").replace(new RegExp("\\s*$"), "");
};
DesktopBrowser.Client.Utils.JsExtensions.AsJsArray = function (list){
    throw $CreateException(new System.Exception.ctor(), new Error());
};
DesktopBrowser.Client.Utils.JsExtensions.AsJsArray = function (array){
    throw $CreateException(new System.Exception.ctor(), new Error());
};
DesktopBrowser.Client.Utils.JsExtensions.AsList = function (list){
    throw $CreateException(new System.Exception.ctor(), new Error());
};
DesktopBrowser.Client.Utils.JsExtensions.IndexOf = function (array, item){
    var i = 0;
    for (var $i2 = 0,$l2 = array.length,item2 = array[$i2]; $i2 < $l2; $i2++, item2 = array[$i2]){
        if (item2 == item)
            return i;
        i++;
    }
    return -1;
};
DesktopBrowser.Client.Utils.JsExtensions.Remove = function (array, item){
    var i = 0;
    for (var $i3 = 0,$l3 = array.length,item2 = array[$i3]; $i3 < $l3; $i3++, item2 = array[$i3]){
        if (item2 == item){
            array.splice(i, 1);
            return true;
        }
        i++;
    }
    return false;
};
DesktopBrowser.Client.Utils.JsExtensions.RemoveAt = function (array, index){
    array.splice(index, 1);
};
DesktopBrowser.Client.Utils.JsExtensions.Clear = function (array){
    array.splice(0, array.length);
};
DesktopBrowser.Client.Utils.JsExtensions.Contains = function (array, item){
    for (var $i4 = 0,$l4 = array.length,item2 = array[$i4]; $i4 < $l4; $i4++, item2 = array[$i4]){
        if (item2 == item)
            return true;
    }
    return false;
};
DesktopBrowser.Client.Utils.JsExtensions.Insert = function (array, index, item){
    array.splice(index, 0, item);
};
DesktopBrowser.Client.Utils.jQueryExtensions = function (){
};
DesktopBrowser.Client.Utils.jQueryExtensions.isChecked = function (j, value){
    if (arguments.length == 1)
        return j.attr("checked");
    else {
        j.attr("checked", value);
        return undefined;
    }
};
DesktopBrowser.Client.Utils.jQueryExtensions.val = function (j, visible){
    if (visible)
        j.show();
    else
        j.hide();
};
DesktopBrowser.Client.SiteProxy = function (){
    this.DataClient = null;
    this.DataClient = new DesktopBrowser.Client.Utils.DataServiceProxy();
};
DesktopBrowser.Client.SiteProxy.prototype.Execute = function (path, callback){
    this.Invoke("Execute", [path], callback);
};
DesktopBrowser.Client.SiteProxy.prototype.Delete = function (path, callback){
    this.Invoke("Delete", [path], callback);
};
DesktopBrowser.Client.SiteProxy.prototype.Invoke = function (methodName, prms, callback){
    var req = {
        AssemblyName: "DesktopBrowser",
        TypeName: "DesktopBrowser.Server.SiteService",
        MethodName: methodName,
        Parameters: prms
    };
    this.DataClient.InvokeAsync(req, $CreateAnonymousDelegate(this, function (t){
        if (t.Error != null){
            alert(t.Error);
        }
        else {
            if (callback != null)
                callback(t.ReturnValue);
        }
    }), false);
};
if (typeof(ReportApp) == "undefined")
    var ReportApp = {};
if (typeof(ReportApp.client) == "undefined")
    ReportApp.client = {};
ReportApp.client.PropHelper = function (){
};
ReportApp.client.PropHelper.prototype.Prop = function (prop){
    return ReportApp.client.Utils.Prop(prop);
};
ReportApp.client.Extensions2 = function (){
};
ReportApp.client.Extensions2.ToFloatOrNull = function (s){
    var x = parseFloat(s);
    if (isNaN(x))
        return null;
    return x;
};
ReportApp.client.Extensions2.ToIntOrNull = function (s){
    var x = parseInt(s);
    if (isNaN(x))
        return null;
    return x;
};
ReportApp.client.Extensions2.Abs = function (x){
    return Math.abs(x);
};
ReportApp.client.Extensions2.ForEachWithPrev$1 = function (list, action){
    var prev = Default(T);
    for (var $i5 = 0,$l5 = list.length,item = list[$i5]; $i5 < $l5; $i5++, item = list[$i5]){
        action(item, prev);
        prev = item;
    }
};
ReportApp.client.Extensions2.ItemProp$1 = function (list, prop){
    return ReportApp.client.Utils.Prop(prop);
};
ReportApp.client.Extensions2.ToDate = function (yyyy_mm_dd){
    if (Q.isNullOrEmpty(yyyy_mm_dd))
        return null;
    return Date.tryParseExact(yyyy_mm_dd, "yyyy-MM-dd");
};
ReportApp.client.Extensions2.ToDefaultDateString = function (date){
    if (date == null)
        return null;
    return date.format("yyyy-MM-dd");
};
ReportApp.client.Extensions2.ToDateValue = function (yyyy_mm_dd){
    return ReportApp.client.Extensions2.ToDate(yyyy_mm_dd).valueOf();
};
ReportApp.client.Extensions2.Trigger = function (action){
    if (action != null)
        action();
};
ReportApp.client.Extensions2.GetPropertyName$1 = function (obj, prop){
    return ReportApp.client.Utils.Prop(prop);
};
ReportApp.client.Extensions2.InvokeAsyncParallel = function (list, finalCallback){
    var count = 0;
    var total = list.length;
    var cb = function (){
        count++;
        if (count == total){
            ReportApp.client.Extensions2.Trigger(finalCallback);
        }
    };
    list.forEach(function (t){
        t(cb);
    });
};
ReportApp.client.Extensions2.GetCreateChildDivWithClass = function (el, className){
    var ch = el.children("." + className);
    if (ch.length == 0)
        ch = $("<div/>").addClass(className).appendTo(el);
    return ch;
};
ReportApp.client.Extensions2.DataItem$1 = function (j){
    return j.data("DataItem");
};
ReportApp.client.Utils = function (){
};
ReportApp.client.Utils.data = null;
ReportApp.client.Utils.CalcChangePct = function (from, to){
    var pct = ((to / from) - 1);
    return pct;
};
ReportApp.client.Utils.ObjToClass = function (obj, defaultTypeForNull){
    var sb =  [];
    var mappings = (function (){
        var $v1 = new Object();
        $v1 ["object"] = "JsObject";
        $v1 ["number"] = "JsNumber";
        $v1 ["boolean"] = "JsBoolean";
        $v1 ["string"] = "JsString";
        return $v1;
    })();
    sb.push("public class Obj");
    sb.push("{");
    for (var p in obj){
        var value = obj[p];
        var type = typeof(value);
        var type2 = (mappings[type] != null ? mappings[type] : type);
        if (value == null)
            type2 = (defaultTypeForNull != null ? defaultTypeForNull : "object");
        sb.push("public " + type2 + " " + p + " { get; set; }");
    }
    sb.push("}");
    return sb.join("\n");
};
ReportApp.client.Utils.PropHelper = function (){
    var x = new ReportApp.client.PropHelper();
    return x.Prop;
};
ReportApp.client.Utils.Prop = function (prop){
    var code;
    if (prop["isDelegate"])
        code = prop["func"].toString();
    else
        code = prop.toString();
    return code.substringBetween(".", ";");
};
ReportApp.client.Utils.listToMatrix = function (list, xProp, yProp, valueProp, aggregateFunc, yieldCallback){
    if (aggregateFunc == null)
        aggregateFunc = function (values){
            return values.sum();
        };
    var xPropSelector = Q.createSelectorFunction(xProp);
    var yPropSelector = Q.createSelectorFunction(yProp);
    var valuePropSelector = Q.createSelectorFunction(valueProp);
    var xs = list.select(xPropSelector).distinct();
    var ys = list.select(yPropSelector).distinct();
    xs.forEach(function (x, xIndex){
        var row =  [x];
        ys.forEach(function (y, yIndex){
            var values = list.where(function (t){
                return xPropSelector(t) == x && yPropSelector(t) == y;
            }).select(valuePropSelector);
            var aggregated = aggregateFunc(values);
            yieldCallback(x, y, aggregated, xIndex, yIndex);
        });
    });
};
ReportApp.client.Utils.listToMatrixRows = function (list, xProp, yProp, valueProp, aggregateFunc){
    var header =  [];
    var rows =  [];
    ReportApp.client.Utils.listToMatrix(list, xProp, yProp, valueProp, aggregateFunc, function (x, y, value, xIndex, yIndex){
        if (xIndex == 0){
            if (yIndex == 0)
                header.push(xProp);
            header.push(y);
        }
        if (yIndex == 0)
            rows[xIndex] =  [x, value];
        else
            rows[xIndex].push(value);
    });
    rows.insert(0, header);
    return rows;
};
ReportApp.client.Utils.listToMatrixObject = function (list, xProp, yProp, valueProp, aggregateFunc){
    var byX = new Object();
    ReportApp.client.Utils.listToMatrix(list, xProp, yProp, valueProp, aggregateFunc, function (x, y, value, xIndex, yIndex){
        var xx = x;
        var yy = y;
        if (byX[xx] == null)
            byX[xx] = new Object();
        byX[xx][yy] = value;
    });
    return byX;
};
ReportApp.client.Utils.cleanUpRows = function (rows){
    rows.forEach(function (row){
        row.forEach(function (value, i){
            if (value === undefined)
                row[i] = null;
        });
    });
    return rows;
};
ReportApp.client.Utils.clearTextNodes = function (el){
    if (el == null)
        el = document.body;
    $(el).find("*+*").toArray().forEach(function (el2){
        var prev = el2.previousSibling;
        while (prev != null && prev.nodeType == 3){
            var tmp = prev;
            prev = prev.previousSibling;
            tmp.remove();
        }
    });
};
ReportApp.client.Utils.createTabControl = function (div){
    var tabs = div.children("div");
    var ul = div.getAppend("ul.nav.nav-tabs");
    var lis = ul.getAppendRemove("li", tabs.length).toArray();
    var btns = tabs.toArray().select(function (tab, i){
        var li = $(lis[i]);
        var btn = li.getAppend("a").text(tab.title).data("target", "#" + tab.id);
        tab.title = "";
        return btn[0];
    });
    var btns2 = $(btns);
    btns2.mousedown(function (e){
        e.preventDefault();
        var target = $(e.target);
        target.tab("show");
        var tab = $(target.data("target"));
        tab.trigger("tabchanged");
    });
    div.getAppend(".tab-content").append(tabs);
    tabs.addClass("tab-pane");
    tabs.first().addClass("active");
    btns2.first().tab("show");
};
ReportApp.client.Utils._Unwrap = function (obj){
    var keys = Object.keys(obj);
    if (keys.length == 2 && keys.contains("_value") && keys.contains("_name")){
        return obj["_value"];
    }
    return obj;
};
ReportApp.client.Utils._xmlToJson = function (el){
    if (el.nodeType == 3)
        return el.data;
    if (el.nodeType != 1)
        return undefined;
    var obj = new Object();
    obj["_name"] = el.nodeName;
    for (var i = 0; i < el.attributes.length; i++){
        var att = el.attributes[i];
        obj[att.name] = att.value;
    }
    for (var i = 0; i < el.childNodes.length; i++){
        var node2 = el.childNodes[i];
        if (node2.nodeType == 1){
            var el2 = node2;
            var prop = el2.nodeName;
            var objValue = obj[prop];
            if (objValue != null){
                var list;
                if (objValue instanceof Array){
                    list = objValue;
                }
                else {
                    list =  [objValue];
                    obj[el2.nodeName] = list;
                }
                list.push(ReportApp.client.Utils._Unwrap(ReportApp.client.Utils._xmlToJson(el2)));
                continue;
            }
            obj[el2.nodeName] = ReportApp.client.Utils._Unwrap(ReportApp.client.Utils._xmlToJson(el2));
        }
        else {
            var value = ReportApp.client.Utils._xmlToJson(node2);
            obj._value = value;
        }
    }
    return obj;
};
ReportApp.client.Utils.xmlToJson = function (xml){
    if (typeof(xml) == "string")
        xml = $.parseXML(xml);
    var el = xml.documentElement;
    var obj = ReportApp.client.Utils._xmlToJson(el);
    return obj;
};
ReportApp.client.Utils.parseDutchFloat = function (s){
    s = s.replaceAll(".", "d").replaceAll(",", ".").replaceAll("d", ",");
    return parseFloat(s);
};
ReportApp.client.Utils.proxy = function (url, q, data, cb){
    var qurl = url;
    if (q != null)
        qurl = url += "?" + QueryString.stringify(q);
    var q2 = {
        url: qurl
    };
    var x = {
        url: "proxy.ashx?" + $.param(q2),
        data: data,
        success: function (t, b, c){
            if (cb != null)
                cb(t, null);
        },
        error: function (jqXHR, textStatus, errorThrown){
            if (cb != null)
                cb(Default(T), errorThrown);
        }
    };
    x.method = data != null ? "POST" : "GET";
    $.ajax(x);
};
DesktopBrowser.Client.Utils.DataServiceProxy = function (){
    this.DataServiceUrl = null;
    this.DataServiceUrl = "DataService.ashx";
};
DesktopBrowser.Client.Utils.DataServiceProxy.CreateRequest = function (){
    if (window.XMLHttpRequest)
  return new XMLHttpRequest();

else if (window.ActiveXObject)
     return new ActiveXObject('MSXML2.XMLHTTP.3.0');
else
    throw new Error('Your browser does not support ajax requests');
};
DesktopBrowser.Client.Utils.DataServiceProxy.WebGetAsync = function (url, callback){
    var req = DesktopBrowser.Client.Utils.DataServiceProxy.CreateRequest();
    req.open("GET", url, true);
    req.onreadystatechange = function (){
        if (req.readyState == 4){
            callback(req);
        }
    };
    req.send(null);
};
DesktopBrowser.Client.Utils.DataServiceProxy.WebPostFormAsync = function (url, form, callback){
    var req = DesktopBrowser.Client.Utils.DataServiceProxy.CreateRequest();
    req.open("POST", url, true);
    req.setRequestHeader("content-type", "application/x-www-form-urlencoded");
    req.onreadystatechange = function (){
        if (req.readyState == 4){
            callback(req);
        }
    };
    var sb =  [];
    DesktopBrowser.Client.Utils.DataServiceProxy.SerializeForm(form, sb);
    req.send(sb.join(""));
};
DesktopBrowser.Client.Utils.DataServiceProxy.SerializeForm = function (form, sb){
    var first = true;
    for (var p in form){
        if (first)
            first = false;
        else
            sb.push("&");
        sb.push(p);
        sb.push("=");
        sb.push(encodeURIComponent(form[p]));
    }
};
DesktopBrowser.Client.Utils.DataServiceProxy.prototype.InvokeAsync = function (req, callback, useGetMethod){
    var callback2 = $CreateAnonymousDelegate(this, function (t){
        var res = {};
        if (t.status == 200){
            var code = t.responseText;
            res = JSON.parse(code);
        }
        else {
            res.Error = "Http error code " + t.status + ", " + t.statusText;
        }
        callback(res);
    });
    var url = this.DataServiceUrl;
    var sb =  [];
    if (useGetMethod){
        sb.push(url, "?z=z");
        DesktopBrowser.Client.Utils.DataServiceProxy.SerializeToQueryString(req, sb);
        url = sb.join("");
        DesktopBrowser.Client.Utils.DataServiceProxy.WebGetAsync(url, callback2);
    }
    else {
        var body = JSON.stringify(req);
        DesktopBrowser.Client.Utils.DataServiceProxy.WebPostFormAsync(url, new Object({
            req: body
        }), callback2);
    }
};
DesktopBrowser.Client.Utils.DataServiceProxy.SerializeToQueryString = function (req, sb){
    if (req.AssemblyName != null)
        sb.push("&a=" + req.AssemblyName);
    if (req.TypeName != null)
        sb.push("&t=" + req.TypeName);
    if (req.MethodName != null)
        sb.push("&m=" + req.MethodName);
    if (req.InstanceSessionKey != null)
        sb.push("&isk=" + req.InstanceSessionKey);
    if (req.Parameters != null){
        var prms = req.Parameters;
        for (var i = 0; i < prms.length; i++){
            sb.push("&p");
            sb.push((i + 1).toString());
            sb.push("=");
            sb.push(encodeURIComponent(prms[i].toString()));
        }
    }
};
DesktopBrowser.Keys = function (){
};
DesktopBrowser.Keys.Enter = 13;
DesktopBrowser.Keys.PageUp = 33;
DesktopBrowser.Keys.PageDown = 34;
DesktopBrowser.Keys.End = 35;
DesktopBrowser.Keys.Home = 36;
DesktopBrowser.Keys.Up = 38;
DesktopBrowser.Keys.Down = 40;
DesktopBrowser.ClientExtensions = function (){
};
DesktopBrowser.ClientExtensions.RegexEscape = function (text){
    return text.replace(new RegExp("[-[\\]{}()*+?.,\\\\^$|#\\s]", "g"), "\\$&");
};

