/* Generated by SharpKit 5 v5.4.8 */

var Selector = null;
var SiteProxy = null;
var PageSize = 10;
SiteProxy = new DesktopBrowser.Client.SiteProxy();
function DefaultClient_Load(){
    if (Data.MoreAvailable === false){
        $(".Pager .Next").addClass("disabled").attr("disabled", "disabled");
    }
    else
        null;
    Selector = new DesktopBrowser.Selector();
    Selector.Selected = function (t){
        t.className = "Selected";
        SaveSelection($(t).find(".NameCell A").text());
    };
    Selector.UnSelected = function (t){
        t.className = "";
    };
    UpdateClock();
    RestoreSelection();
    $(window).keydown(function (e){
        if (e.target != null && e.target.nodeName == "INPUT")
            return null;
        else
            null;
        if (e.which == DesktopBrowser.Keys.Up){
            e.preventDefault();
            Up();
        }
        else if (e.which == DesktopBrowser.Keys.Down){
            e.preventDefault();
            Down();
        }
        else if (e.which == DesktopBrowser.Keys.PageDown){
            e.preventDefault();
            PageDown();
        }
        else if (e.which == DesktopBrowser.Keys.PageUp){
            e.preventDefault();
            PageUp();
        }
        else if (e.which == DesktopBrowser.Keys.Enter){
            e.preventDefault();
            Enter();
        }
        else {
            $("#tbSearch").get(0).focus();
        }
    });
};
function WriteLine(obj){
    document.body.appendChild(document.createTextNode(obj));
    document.body.appendChild(document.createElement("br"));
};
function CanMoveSelection(by){
    return MoveSelection(by, false);
};
function MoveSelection(by, preview){
    var by2 = by;
    var row = $(Selector.SelectedItem);
    if (row.length == 0)
        return false;
    else
        null;
    while (by2 > 0){
        if (row.next().length == 0)
            break;
        else
            null;
        row = row.next();
        by2--;
    }
    while (by2 < 0){
        if (row.prev().length == 0)
            break;
        else
            null;
        row = row.prev();
        by2++;
    }
    if (row.length == 0 || by == by2)
        return false;
    else
        null;
    if (!preview){
        var row2 = row.get(0);
        Select(row2);
    }
    else
        null;
    return true;
};
function Select(row){
    Selector.Select(row);
    var pos = $(row).offset();
    if (pos.top < window.pageYOffset){
        row.scrollIntoView(true);
    }
    else if (pos.top > window.pageYOffset + window.innerHeight){
        row.scrollIntoView(false);
    }
    else
        null;
};
function PageDown(){
    return MoveSelection(PageSize * 1, false);
};
function PageUp(){
    return MoveSelection(PageSize * -1, false);
};
function Enter(){
    var anchor = $(Selector.SelectedItem).find("a").get(0);
    if (anchor.nodeName == "A"){
        SimulateClick(anchor);
        return true;
    }
    else
        null;
    return false;
};
function SelectFirstItem(){
    var first = $("grdFiles TBODY TR").first().get(0);
    if (first != null){
        Select(first);
        return true;
    }
    else
        null;
    return false;
};
function Down(){
    if (!MoveSelection(1, false))
        return SelectFirstItem();
    else
        null;
    return false;
};
function Up(){
    if (!MoveSelection(-1, false))
        return SelectFirstItem();
    else
        null;
    return false;
};
function RestoreSelection(){
    var folder = $("#tbFilename").val();
    var filename = GetStorageItem(folder);
    if (filename != null && filename.length > 0){
        $("#grdFiles .NameCell A").each(function (i, el){
            var x = $(el);
            if (x.text() == filename){
                Selector.Select(x.parents("tr").first().get(0));
                return false;
            }
            else
                null;
        });
    }
    else
        null;
};
function GetStorageItem(key){
    return window.localStorage.getItem(key);
};
function SetStorageItem(key, value){
    window.localStorage.setItem(key, value);
};
function SaveSelection(filename){
    var folder = $("#tbFilename").val();
    var nextYear = new Date();
    nextYear.setFullYear(nextYear.getFullYear() + 4);
    SetStorageItem(folder, filename);
};
function UpdateClock(){
    $("#divTime").text(new Date().format("h:MM tt"));
    $("#divDate").text(new Date().format("ddd, mmm d"));
    window.setTimeout(UpdateClock, 5000);
};
function Execute(path){
    new DesktopBrowser.Client.SiteProxy().Execute(path, null);
};
function OpenFile(path){
    new DesktopBrowser.Client.SiteProxy().Execute(path, null);
};
function GetSelectedPath(){
    if (Selector.SelectedItem == null)
        return null;
    else
        null;
    var filePath = $(Selector.SelectedItem).find(".ihFilePath").val();
    return filePath;
};
function btnDelete_click(){
    var path = GetSelectedPath();
    if (path == null)
        return null;
    else
        null;
    if (!window.confirm("are you sure you want to permanantly delete the path: " + path))
        return null;
    else
        null;
    SiteProxy.Delete(path, function (t){
        window.location.reload();
    });
};
function Filter(el, exp){
    var x = $(el);
    x.parents("tr").first().toggle(x.text().search(exp) >= 0);
};
function tbFolder_keydown(e){
    if (e.keyCode == 13){
        Go();
    }
    else
        null;
};
function Go(){
    var newPath = $("#tbFolder").val();
    window.location.href = "?p=" + encodeURIComponent(newPath);
};
function btnGo_click(e){
    Go();
};
function tbSearch_keyup(e){
    var search = $("#tbSearch").val();
    var exp = new RegExp(DesktopBrowser.ClientExtensions.RegexEscape(search), "i");
    $("#grdFiles .NameCell A").each(function (i, el){
        Filter(el, exp);
    });
};
function SimulateClick(anchor){
    var a = $(anchor);
    a.trigger("click", null);
    var href = a.attr("href");
    if (href != null && href.length > 0){
        var target = a.attr("target");
        if (target == "_blank")
            window.open(href, "");
        else
            window.location.href = href;
    }
    else
        null;
};
if (typeof(DesktopBrowser) == "undefined")
    var DesktopBrowser = {};
DesktopBrowser.Selector = function (){
    this.Selected = null;
    this.UnSelected = null;
    this.SelectedItem = null;
};
DesktopBrowser.Selector.prototype.Select = function (el){
    if (this.SelectedItem == el)
        return null;
    else
        null;
    var unselected = this.SelectedItem;
    this.SelectedItem = el;
    if (unselected != null && this.UnSelected != null)
        this.UnSelected(unselected);
    else
        null;
    if (this.SelectedItem != null && this.Selected != null)
        this.Selected(this.SelectedItem);
    else
        null;
};

