/* Generated by SharpKit 5 v5.4.9 */

jQuery.fn.Grid = function (opts){
    this.toArray().forEach($CreateAnonymousDelegate(this, function (el){
        var el2 = $(el);
        var grid = el2.data("Grid");
        if (grid != null){
            grid.Options = opts;
            grid.El = $(el);
            grid.Render();
        }
        else {
            grid = new dbr.grid.Grid(el2, opts);
            el2.data("Grid", grid);
            grid.Render();
        }
    }));
    return this;
};
$Inherit(jQuery, $);

