name: Node.js CI

on:
    create:
        tags:
            - "*"

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i -g npm
            - run: npm install
            - run: pwd
            - run: cd shared; npm install
            - run: cd client; npm install
            - run: cd server; npm install
            - run: cd app; npx tsc
            - run: cd client; npm run build
            - run: cd client; npm prune --production
            - run: rm -rf server
            - run: rm -rf scripts
            - run: rm -rf shared
            - run: npm run make
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      out/make/zip/darwin/x64/*.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
